name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: [self-hosted, linux, x64]
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} events."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: check info
        run: |
              cat cat /proc/cpuinfo
              if [ -f /.dockerenv ]; then
                echo "I'm inside matrix ;(";
              else
                echo "I'm living in real world!";
              fi

      - name: build gem5
        run: |
          #     echo "nothing happens here"
              scons build/ALL/gem5.opt -j 24
          #     # scons build/ALL/gem5.fast -j4 --no-compress-debug --ignore-style
      - name: run x86 tests without initial build
        run: |
              cd tests
              ./main.py run gem5/x86-boot-tests -j24
          #     # ./main.py run -j4 -t4 gem5 -vv && scons -C .. --no-compress-debug --ignore-style build/ARM/unittests.opt
          # gcr.io/gem5-test/ubuntu-20.04_all-dependencies:v22-0
      - run: echo "ğŸ This job's status is ${{ job.status }}."
